export const API_ENDPOINTS = {
  AUTH: {
    REGISTER: '/auth/register/',
    VERIFY_EMAIL: '/auth/verify-email/',
    RESEND_CODE: '/auth/resend-code/',
    LOGIN: '/auth/login/',
    ONBOARDING_COMPLETE: '/auth/onboarding/complete/',
    APPLICATION_STATUS: '/auth/application-status/',
    REFRESH: '/auth/token/refresh/',
    VERIFY_TOKEN: '/auth/token/verify/',
    ME: '/auth/me/',
    FORGOT_PASSWORD: '/auth/forgot-password/',
    RESET_PASSWORD: '/auth/reset-password/',
  },
  ADMIN: {
    ROLE_APPLICATIONS: '/auth/admin/role-applications/',
    APPROVE_ROLE_APPLICATION: (id: string) => `/auth/admin/role-applications/${id}/approve/`,
    REJECT_ROLE_APPLICATION: (id: string) => `/auth/admin/role-applications/${id}/reject/`,
  },
  DATASETS: {
    LIST: '/marketplace/datasets/',
    DETAIL: (id: string) => `/marketplace/datasets/${id}/`,
    UPLOAD: '/marketplace/datasets/upload/',
  },
  DOCUMENTS: {
    SUBMIT: '/documents/submit/',
    MY_SUBMISSIONS: '/documents/my-submissions/',
    MY_SUBMISSION_DETAIL: (id: string) => `/documents/my-submissions/${id}/`,
  },
  TASKS: {
    QUEUE: '/processing/my-assignments/',
    MY_ASSIGNMENTS: '/processing/my-assignments/',
    ACCEPT_ASSIGNMENT: (id: string) => `/processing/assignments/${id}/accept/`,
    DECLINE_ASSIGNMENT: (id: string) => `/processing/assignments/${id}/decline/`,
    GET_CHUNKS: (id: string) => `/processing/assignments/${id}/chunks/`,
    GET_PROGRESS: (id: string) => `/processing/assignments/${id}/progress/`,
    SUBMIT_ANNOTATION: (chunkId: string) => `/processing/chunks/${chunkId}/annotate/`,
    SUBMIT: (id: string) => `/processing/tasks/${id}/submit/`,
  },
  EXPERT: {
    QUEUE: '/processing/expert/tasks/',
    ACCEPT_TASK: (id: string) => `/processing/expert/tasks/${id}/accept/`,
    DECLINE_TASK: (id: string) => `/processing/expert/tasks/${id}/decline/`,
    GET_CHUNKS: (id: string) => `/processing/expert/tasks/${id}/chunks/`,
    GET_PROGRESS: (id: string) => `/processing/expert/tasks/${id}/progress/`,
    RESOLVE_CHUNK: (chunkId: string | number) => `/processing/expert/chunks/${chunkId}/resolve/`,
    SUBMIT_REVIEW: (chunkId: string) => `/processing/expert/chunks/${chunkId}/review/`,
  },
};
