export const API_ENDPOINTS = {
  AUTH: {
    REGISTER: '/auth/register/',
    VERIFY_EMAIL: '/auth/verify-email/',
    RESEND_CODE: '/auth/resend-code/',
    LOGIN: '/auth/login/',
    PROFILE: '/auth/profile/',
    ONBOARDING_COMPLETE: '/auth/onboarding/complete/',
    APPLICATION_STATUS: '/auth/application-status/',
    REFRESH: '/auth/token/refresh/',
    VERIFY_TOKEN: '/auth/token/verify/',
    ME: '/auth/me/',
    FORGOT_PASSWORD: '/auth/forgot-password/',
    RESET_PASSWORD: '/auth/reset-password/',
  },
  ADMIN: {
    ROLE_APPLICATIONS: '/auth/admin/role-applications/',
    APPROVE_ROLE_APPLICATION: (id: string) => `/auth/admin/role-applications/${id}/approve/`,
    REJECT_ROLE_APPLICATION: (id: string) => `/auth/admin/role-applications/${id}/reject/`,
    USERS: '/auth/admin/users/',
    DEACTIVATE_USER: (userId: string) => `/auth/admin/users/${userId}/deactivate/`,
    REACTIVATE_USER: (userId: string) => `/auth/admin/users/${userId}/reactivate/`,
  },
  DATASETS: {
    LIST: '/marketplace/datasets/',
    DETAIL: (id: string) => `/marketplace/datasets/${id}/`,
    UPLOAD: '/marketplace/datasets/upload/',
    PURCHASE: (id: string) => `/marketplace/datasets/${id}/purchase/`,
  },
  PURCHASES: {
    LIST: '/marketplace/purchases/',
    DOWNLOAD: (purchaseId: string, assetId: string) => `/marketplace/purchases/${purchaseId}/assets/${assetId}/download/`,
  },
  PAYMENTS: {
    WALLET_DETAILS: '/payments/wallet-details/',
    BANKS: '/payments/banks/',
    WITHDRAWALS: '/payments/withdrawals/',
    WITHDRAWALS_LIST: '/payments/withdrawals/list/',
    PAYOUT_RULES: '/payments/payout-rules/',
    PAYOUT_RULES_UPDATE: (id: string) => `/payments/payout-rules/${id}/`,
  },
  SCORING: {
    SCORE_CONFIGS: '/scoring/score-configs/',
  },
  ANALYTICS: {
    ANNOTATOR_DASHBOARD: '/analytics/annotator/dashboard/',
    ANNOTATOR_OVERVIEW: '/analytics/annotator/overview/',
    CONTRIBUTOR_DASHBOARD: '/analytics/contributor/dashboard/',
    BUYER_DASHBOARD: '/analytics/buyer/dashboard/',
    ADMIN_DASHBOARD: '/analytics/admin/dashboard/',
    EXPERT_DASHBOARD: '/analytics/expert/dashboard/',
    EXPERT_OVERVIEW: '/analytics/expert/overview/',
  },
  DOCUMENTS: {
    SUBMIT: '/documents/submit/',
    MY_SUBMISSIONS: '/documents/my-submissions/',
    MY_SUBMISSION_DETAIL: (id: string) => `/documents/my-submissions/${id}/`,
  },
  TASKS: {
    QUEUE: '/processing/my-assignments/',
    MY_ASSIGNMENTS: '/processing/my-assignments/',
    NLP_TASKS: '/nlp/tasks/',
    NLP_TASK_DETAIL: (taskId: string) => `/nlp/tasks/${taskId}/`,
    NLP_TASK_PROGRESS: (taskId: string) => `/nlp/tasks/${taskId}/progress/`,
    NLP_ANNOTATE_CHUNK: (chunkId: string) => `/nlp/chunks/${chunkId}/annotate/`,
    NLP_ACCEPT_TASK: (taskId: string) => `/nlp/tasks/${taskId}/accept/`,
    NLP_DECLINE_TASK: (taskId: string) => `/nlp/tasks/${taskId}/decline/`,
    ACCEPT_ASSIGNMENT: (id: string) => `/processing/assignments/${id}/accept/`,
    DECLINE_ASSIGNMENT: (id: string) => `/processing/assignments/${id}/decline/`,
    GET_CHUNKS: (id: string) => `/processing/assignments/${id}/chunks/`,
    GET_PROGRESS: (id: string) => `/processing/assignments/${id}/progress/`,
    SUBMIT_ANNOTATION: (chunkId: string) => `/processing/chunks/${chunkId}/annotate/`,
    SUBMIT: (id: string) => `/processing/tasks/${id}/submit/`,
  },
  EXPERT: {
    QUEUE: '/processing/expert/tasks/',
    ACCEPT_TASK: (id: string) => `/processing/expert/tasks/${id}/accept/`,
    DECLINE_TASK: (id: string) => `/processing/expert/tasks/${id}/decline/`,
    GET_CHUNKS: (id: string) => `/processing/expert/tasks/${id}/chunks/`,
    GET_PROGRESS: (id: string) => `/processing/expert/tasks/${id}/progress/`,
    RESOLVE_CHUNK: (chunkId: string | number) => `/processing/expert/chunks/${chunkId}/resolve/`,
    SUBMIT_REVIEW: (chunkId: string) => `/processing/expert/chunks/${chunkId}/review/`,
  },
  NOTIFICATIONS: {
    LIST: '/notifications/',
    MARK_READ: (id: string) => `/notifications/${id}/read/`,
    MARK_ALL_READ: '/notifications/read-all/',
    UNREAD_COUNT: '/notifications/unread-count/',
  },
};
